"""Independent compatibility declaration for Pairwise Review Sessions."""

PAIRWISE_REVIEW_APP_VERSION = "1.1.0"
PAIRWISE_REVIEW_SESSION_SCHEMA_VERSION = "1.1-draft"
PAIRWISE_REVIEW_SEMANTICS_VERSION = "1.1"

SUPPORTED_PAIRWISE_REVIEW_SESSION_SCHEMA_VERSIONS = frozenset({PAIRWISE_REVIEW_SESSION_SCHEMA_VERSION})
SUPPORTED_PAIRWISE_REVIEW_SEMANTICS_VERSIONS = frozenset({PAIRWISE_REVIEW_SEMANTICS_VERSION})
SUPPORTED_PAIRWISE_GOLD_SCHEMA_VERSIONS = frozenset({"1.0-draft"})
