"""LOTM Translator v2 foundation (Architecture phases 0–2)."""

NORMALIZED_SCHEMA_VERSION = "2.2-draft"
SOURCE_MANIFEST_SCHEMA_VERSION = "1.3"
GOLD_SCHEMA_VERSION = "1.0-draft"
PARAGRAPHIZATION_SCHEMA_VERSION = "1.0-draft"
EPUB_PARAGRAPHIZATION_SCHEMA_VERSION = "1.0-draft"
SOURCE_CHAPTER_MAP_SCHEMA_VERSION = "1.0-draft"
