"""LOTM Translator v2 foundation (Architecture phases 0–2)."""

NORMALIZED_SCHEMA_VERSION = "2.1-draft"
SOURCE_MANIFEST_SCHEMA_VERSION = "1.1"
GOLD_SCHEMA_VERSION = "1.0-draft"
PARAGRAPHIZATION_SCHEMA_VERSION = "1.0-draft"
